.TH WSA 1 "July 2024" "1.0" "WiFi Stability Analyzer"
.SH NAME
wsa \- WiFi Stability Analyzer
.SH SYNOPSIS
.B wsa
.I duration_in_seconds
.SH DESCRIPTION
\fBWSA\fP is a command-line tool designed to monitor and log the stability of your WiFi connection. It measures signal strength, connectivity, and network speed over a specified duration and logs the results for analysis.
.SH OPTIONS
.TP
\fIduration_in_seconds\fP
Specifies the duration for which the analyzer should run.
.SH EXAMPLES
.TP
Run the analyzer for 30 seconds:
.B wsa 30
.SH AUTHOR
Written by Nick DeVeau.
